react-native-oh-library/RNOHDCS

react-native-error-boundary/ErrorBoundaryTest.tsx
修改react-native-error-boundary测试demo：将Button、TestCase组件修改为testerino库中的
close #362
=> test: 修改react-native-error-boundary测试demo

@itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample10.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample11.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample12.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample13.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample14.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample15.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample16.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample17.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample18.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample19.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample2.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample20.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample21.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample22.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample23.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample24.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample25.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample26.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample27.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample3.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample4.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample5.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample6.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample7.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample8.jsx, @itenl/react-native-scrollable-tabview/ScrollableTabviewExample-CAPI/ScrollableTabviewExample9.jsx
修改@itenl/react-native-scrollable-tabview库测试demo
1.在CAPI化下，该库为滑动组件库会和RN的滑动组件产生冲突。
2.同一组件在同一页面文件下，可能会导致生命周期互相干扰。故提取每个用例进行一个页面
3.每个页面是对应用例，可以保证用例的书写方式均为开发者常用开发写法。同一页面书写，可能会出现组件重命名等，让整体代码混乱，难读懂.
#381
=> test:修改@itenl/react-native-scrollable-tabview库测试demo

react-native-device-info/RNDeviceInfoDemo.tsx, react-native-device-info/test/RNDeviceInfoTest.tsx
- 修改react-native-device-info 的测试demo。
Close : 修改isLowRamDevice 接口返回结果显示不正常的问题 [#469](https://github.com/react-native-oh-library/RNOHDCS/issues/469)。
=> test:修改react-native-device-info 的测试demo

react-native-material-menu/ReactNativeMaterialMenuDemo.tsx
新增react-native-material-menu的test用例
=> test: 添加react-native-material-menu测试demo

react-native-device-info/RNDeviceInfoDemo.tsx, react-native-device-info/test/RNDeviceInfoTest.tsx
*  修改react-native-device-info 测试demo
Close : 新增hasNotch、getMacAddress、getUniqueId接口测试 [#501](https://github.com/react-native-oh-library/RNOHDCS/issues/501)。
=> test:修改react-native-device-info 测试demo

react-native-image-resizer/ImageResizerDemo.tsx
- 修改react-native-image-resizer demo，新增入参选择按钮。
=> test:修改react-native-image-resizer demo

react-native-screenshot-prevent/TestNativeScreenshotPreventDemo.tsx
该demo覆盖了RNScreenshotPrevent.enabled(true)、RNScreenshotPrevent.enabled(false)以及RNScreenshotPrevent.addListener接口的测试用例，RNScreenshotPrevent.enableSecureView()、RNPreventScreenshot.enableSecureView(imgUri)及RNScreenshotPrevent.disableSecureView()接口做遗留，暂未覆盖
本次修改要点：
+ 新增新增react-native-screenshot-prevent的demo
=> test:新增react-native-screenshot-prevent的demo #612

react-native-permissions/PermissionsExample.tsx
修改react-native-permissions的示例demo
已测的接口：check、checkNotifications、openSettings、request、requestNotifications、checkMultiple、requestMultiple
未测的接口：checkLocationAccuracy、requestLocationAccuracy、openPhotoPicker
=> test: 修改react-native-permissions的示例demo

react-native-calendar/CalendarExample.tsx
在demo中Calendar组件已测的接口方法有onDayPress，已测的接口属性有theme，style， headerStyle， monthFormat，customHeader， initialDate， minDate，maxDate，markedDates，
hideExtraDays， hideArrows，disableArrowLeft，disableArrowRight，dayComponent等；
未测的接口方法有onDayLongPress，onMonthChange， onVisibleMonthsChange，onPressArrowLeft，onPressArrowRight，未测的属性有：hideDayNames，displayLoadingIndicator，
firstDay，arrowsHitSlop，renderArrow，customHeaderTitle，disableAllTouchEventsForDisabledDays，disableAllTouchEventsForInactiveDays等。
在CalendarList的组件demo中已测试的属性接口有futureScrollRange，pastScrollRange，calendarStyle，calendarWidth；未测试的接口属性有showScrollIndicator，
staticHeader，calendarHeight等；
在Agenda组件的demo中测试的接口属性有selected，items，loadItemsForMonth，未测试的属性有onDayChange，onCalendarToggled，
renderKnob，hideKnob，renderEmptyData等属性
=> test: 新增react-native-calendars测试demo

react-native-material-dropdown/DropDownDemo.tsx, react-native-material-dropdown/test/DropDownTest.tsx
这个demo测试，不涉及issues
- 这个功能是什么？
这个PR是为了适配react-native-mertial-dropdown HMOS系统demo和test验证
- 您是如何实现解决方案的？
参照react-native-mertial-dropdown源码修改适配后demo验证
参照react-native-mertial-dropdown源码修改适配demo验证
demo测试路径：https://github.com/MyAndroidNetZWJ/RNOHDCS/tree/main/react-native-material-dropdown
=> test：新增react-native-mertial-dropdown测试用例和demo

react-native-print/PrintDemo.tsx, react-native-print/test/PrintTest.tsx
新增了react-native-print的测试demo和test。
新增了print接口中filePath、jobName两个参数的demo。
参数filePath包括远程uri打印和本地uri打印的demo
=> test: 新增react-native-print测试demo

react-native-phone-number-input/Disable.tsx, react-native-phone-number-input/PNIPropsDemo.tsx, react-native-phone-number-input/index.tsx
修改react-native-phone-number-input测试demo，将disable的测试用例单独放在一个页面，使用NavigationContainer来进行路由跳转。
=> test: 修改react-native-phone-number-input测试demo

react-native-markdown-renderer/TestReactNativeMarkdownRenderer.tsx, react-native-markdown-renderer/test/TestReactNativeMarkdownRendererDemo.tsx
本库基于react-native-markdown-renderer[https://github.com/mientjan/react-native-markdown-renderer]的基础上,增加了对React0.72.5及react18.2.0版本的适配。示例demo覆盖了Heading(1~6)、Tables、Horizontal Rules、Emphasis、Blockquotes、Lists、Links、Images、style属性以及rules属性的测试用例。
本次修改要点：
+ 新增react-native-markdown-renderer测试用例
=> test:新增react-native-markdown-renderer测试用例

react-native-permissions/demo/demo.tsx, react-native-permissions/testCase/TestCase.tsx
修改react-native-permissions的示例demo
已测的接口：check、checkNotifications、openSettings、request、requestNotifications、checkMultiple、requestMultiple
未测的接口：checkLocationAccuracy、requestLocationAccuracy、openPhotoPicker
=> test:修改react-native-permissions的测试用例、demo

react-native-gesture-handler/DrawerLayout.tsx
- 修改了DrawerLayout模块中隐藏显示状态栏属性。
=> test: 修改 react-native-gesture-handler 的测试demo中DrawerLayout场景

react-native-safe-modules/SafeModuleDemo.tsx, react-native-safe-modules/test/SafeModuleExample.tsx
1. 新增react-native-safe-modules的测试用例
2. 一共提供了3个API：create、module、component
3. create、module作用是使用三方库的时候可以换一个写法；component接口在iOS和Android中的功能都不齐全，代码只能执行一部分，功能只有重命名组件
=> test: 新增react-native-safe-modules的测试用例

react-native-quick-base64/demo/QuickBase64Example.tsx, react-native-quick-base64/tester/QuickBase64Test.tsx
新增react-native-quick-base64测试demo,测试用例
1. 新增测试demo和测试用例 
2. 新增测试API包含8个方法函数
- byteLength：获取base64转Unit8Array 后获取Unit8Array的字符数组长度
- btoa：字符串编码base64
- atob：base64解码字符串
- toByteArray 和 fromByteArray：base64和Unit8Array互转
- trimBase64Padding：去除base64编码后的填充字符，例如：'='，'.'  , ' /'等等
- shim：为全局的global/window对象设置btoa，atob编码解码方法
- getNative：获取RN原生的base64ToArrayBuffer 和 base64FromArrayBuffer方法
=> test:新增react-native-quick-base64测试demo,测试用例 (#787)

react-native-mlkit-ocr/Test/OcrTest.tsx, react-native-mlkit-ocr/TestOcrExample.tsx
新增react-native-mlkit-ocr测试demo和测试用例
1. 新增测试demo和测试用例
2. 新增测试API包含2个方法函数
detectFromUri(uri: string)：传入图片的 在线地址 进行OCR识别(参数类型为字符串)
detectFromFile(path：string)：传入图片的 文件地址 进行OCR识别(参数类型为字符串)
=> test: 新增react-native-mlkit-ocr测试demo，新增react-native-mlkit-ocr测试用例(#801)

react-native-async-storage-async-storage/Example/Async-storage-hook.tsx, react-native-async-storage-async-storage/Example/Async-storage.tsx, react-native-async-storage-async-storage/TesterDemo/AsyncStorage-Hook.tsx, react-native-async-storage-async-storage/TesterDemo/AsyncStorage.tsx
- 新增react-native-audio-recorder-player示例代码
- 新增测试用例覆盖全量静态方法,及hook用法
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\lwx1346351\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\lwx1346351\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
</head>
<body link=blue vlink=purple>
getItem(key:   string, [callback]: ?(error: ?Error, result: ?string) => void): Promise | 根据给定的key获取对应的string值
-- | --
setItem(key: string, value: string, [callback]: ?(error: ?Error)   => void): …
=> feat: 新增react-native-async-storage-async-storage示例代码及测试用例

react-native-user-agent/demo/UserAgentDemo.tsx, react-native-user-agent/test/UserAgentTest.tsx
在demo中, UserAgent已测试的接口方法有getUserAgent,getWebViewUserAgent, 已测试的接口常量有systemName,systemVersion,applicationName,applicationVersion,buildNumber
=> test: 新增react-native-user-agent测试demo和测试用例

react-native-button/demo/ReactNativeButtonExample.tsx, react-native-button/test/ReactNativeButtonTest.tsx
在test中react-native-button组件已测的接口方法有onPress，已测的接口属性有style、containerStyle、disabled、accessibilityLabel、childGroupStyle、styleDisabled、disabledContainerStyle等；
=> test: 新增react-native-button测试demo和测试用例

react-native-idle-timer/demo/IdleTimerDemo.tsx, react-native-idle-timer/test/IdleTimerTest.tsx
在demo中IdleTimerManager组件已测的接口方法有setIdleTimerDisable
=> test: 新增react-native-idle-timer测试demo和测试用例

react-native-audio-recorder-player/AudioRecordPlayerExample/Audio-recorder-player.tsx, react-native-audio-recorder-player/AudioRecordPlayerExample/Button.tsx, react-native-audio-recorder-player/test/AudioRecordPlayerExample.tsx, react-native-audio-recorder-player/test/Button.tsx, react-native-audio-recorder-player/test/palette.ts
- 音频录制与播放参照下列功能方法
<body link=blue vlink=purple>
mmssss(milliseconds:number   ):string | 将毫秒数转换为minute:second:milliseconds字符串
-- | --
mmss(milliseconds:number ):string | 将毫秒数转换为minute:second字符串
setSubscriptionDuration(sec: number): Promise<string> | 设置录音机或播放器时的默认回调时间。默认为500ms
addRecordBackListener(callBack:function):void | 录音开始时开始回调将收到currentPosition，currentMetering（如果在   startRecorder 中配置）
removeRecordBackListener(callBack:function):void | 删除   recordBack 监听器
addPlayBackListener(callBack:function):void | 获取原生模块的回调。将收到duration，currentPosition
removePlayBackListener(callBack:function):void | 移除播放监听器
startRecorder(uri?:string,AudioSet?:AudioSet):   Promise<void> | 开始录音。不传递   uri 将会将音频保存在默认位置。
pauseRecorder():   Promise<string> | 暂停录音。 …
=> feat: 新增react-native-audio-recorder-player测试用例及示例代码

react-native-image-crop-picker/ImageCropPickDemo.tsx
- close #888 
- 修改 react-native-image-crop-picker demo
=> fix: 修改 react-native-image-crop-picker demo

@shopify/flash-list/FlashListDemo4.tsx, @shopify/flash-list/test/FlashListTest.tsx
修改flash-list库demo的CellRendererComponent属性的动画执行方式来处理加载时间过长问题
问题现象：CellRendererComponent属性的动画加载时间过长
分析：可通过设置setNativeDriver来使用设备渲染（不通过js渲染形式实现）动画来缩短加载时长
结果：使用setNativeDriver后动画可以快速执行
=> test: 修改flash-list库demo的CellRendererComponent属性的动画加载时间过长问题

react-native-vision-camera/PhotoDemo.tsx
react-native-vision-camera库的拍照demo添加1X和1.4X按钮
无
=> fix:react-native-vision-camera库的拍照demo添加1X和1.4X按钮

react-native-callkeep/CallKeepDemo.tsx, react-native-callkeep/test/CallKeepTestCase.tsx
这个PR主要是提交react-native-callkeep这个RN三方库适配HOMS的测试用例和测试demo，不涉及到issues
- 这个功能是什么？
主要是写react-native-callkeep测试用例来测试HMOS功能是否实现
- 您是如何实现解决方案的？
编写[CallKeepTestCase.tsx和CallKeepDemo.tsx文件
不影响库，只针对测试用例编写
测试demo路径：https://github.com/react-native-oh-library/RNOHDCS/tree/main
=> test：按照要求新增react-native-callkeep测试用例和demo

react-native-svg/tester/svgDemoCases/components/genRect.tsx, react-native-svg/tester/svgDemoCases/genUtil.tsx
- 更改 rect 中的底色为 grey，strokeWidth为2，删除非SVG标准库属性
=> test: 更改 react-native-svg 测试用例

react-native-sensitive-info/test/SensitiveInfoDemo.tsx
- 修改react-native-sensitive-info中cancelFingerprintAuth取消指纹认证的使用方法，添加deleteItem删除键值对的对比用例。
=> test:  修改react-native-sensitive-info测试用例

react-native-tcp-socket/TcpSocketDemo.tsx, react-native-tcp-socket/test/TcpSocketTest.tsx
- 新增react-native-tcp-socket的测试用例和demo，主要实现功能：
TCP/TLS服务器和客户端的创建，数据发送，恢复和暂停,证书查询，关闭连接等接口
https://github.com/user-attachments/assets/7c26383e-120b-4bee-aeb6-6fabac431dc7
=> test:新增react-native-tcp-socket的测试用例和demo

react-native-cameraroll/demo/CamerarollExample.tsx, react-native-cameraroll/test/CamerarollTest.tsx
测试接口：saveAsset、saveToCameraRoll
=> test: 新增react-native-cameraroll测试用例

react-native-default-preference/test/defaultDemo.tsx
- 修改react-native-default-preference的测试demo,添加clearMultiple这个方法的测试用例。
=> test:  修改react-native-default-preference的测试demo

@shopify/flash-list/test/TestIndex.tsx
=> test: 新增flash-list测试用例的导航索引文件

react-native-image-capinsets-next/demo/ImageCapInsetsDemo.tsx, react-native-image-capinsets-next/test/ImageCapInsetsTest.tsx
test: 增加ScrollView到react-native-image-capinsets-next测试用例和demo
=> test: 增加ScrollView到react-native-image-capinsets-next测试用例和demo

react-native-image-capinsets-next/demo/ImageCapInsetsDemo.tsx, react-native-image-capinsets-next/test/ImageCapInsetsTest.tsx
test: 修改react-native-image-capinsets-next的demo和测试用例展示问题修复
=> test: 修改react-native-image-capinsets-next的demo和测试用例展示问题修复

react-native-ssl-pinning/SslPinningDemo.tsx
1:修改react-native-ssl-pinning的demo请求链接
=> test:修改react-native-ssl-pinning的demo请求链接

@op-engineering-op-sqlite/demo/opSqliteDemo.tsx, @op-engineering-op-sqlite/package.json, @op-engineering-op-sqlite/test/TestForOpSqlite.tsx
- 新增@op-engineering-op-sqlite测试用例
- 新增react native 主工程 package.json 对应的 op-sqlite插件配置
- closes: #1284
=> test: 新增@op-engineering-op-sqlite测试用例

react-native-image-crop-picker/Tester/ImageCropPickerDemo.tsx
修改react-native-image-crop-picker测试demo
closed #1366
=> test: 修改react-native-image-crop-picker测试demo

react-native-nfc-manager/NfcManagerDemo.tsx
修改react-native-nfc-manager的测试用例
1.使状态显示的地方保持固定，不会随整体界面的滑动而隐藏
=> test:修改react-native-nfc-manager的测试用例

react-native-incall-manager/test/InCallManagerTest.tsx
- 修改react-native-incall-manager测试demo的顶部文本颜色。
- closes: #1411
=> test：修改react-native-incall-manager测试demo的顶部文本颜色

react-native-switch/test/SwitchDemo.tsx
- 新增renderActiveText和renderInActiveText的测试用例，提供对比效果
=> test:  修改react-native-switch测试demo

react-native-send-intent/SendIntent.tsx, react-native-send-intent/text/SendIntent.tsx
- 这个 PR 解决了哪些 issues？请标记这些 issues，以便合并 PR 后这些 issues 将会被自动关闭
clone #1425 
test:修改react-native-send-intent测试用例
- 您是如何实现解决方案的？
test:修改react-native-send-intent测试用例
无
=> ‘test:修改react-native-send-intent测试用例’

react-native-text-input-mask/demo/TextInputDemo.tsx, react-native-text-input-mask/tester/TextInputDemo.tsx
close: #1440 
- 新增affinityCalculationStrategy和autoskip用例
新增日志输出不同affinityCalculationStrategy计算亲和度值，如下图：
=> test: 新增affinityCalculationStrategy和autoskip用例

react-native-image-marker/ImageMarker.tsx, react-native-image-marker/ImageMarkerNomal.tsx
- 新增透明度0.5的用例
背景图片透明度0.5：
图标透明度0.5：
文字水印背景透明度0.5：
=> test: 新增透明都0.5的用例

rn-sliding-up-panel/page/OnBottomReached.tsx, rn-sliding-up-panel/page/OnMomentumDragEnd.tsx
修改rn-sliding-up-panel测试用例，修改onBottomReached、onMomentumDragEnd部分代码错误
=> test: 修改rn-sliding-up-panel测试用例

react-native-image-marker/ImageMarker.tsx
- 修改react-native-image-marker 缩放用例 图片显示由resizeMode='contain' 改为resizeMode='center'，close: #1612
=> test: 修改react-native-image-marker 缩放用例 图片显示由resizeMode='contain' 改为resizeMode='center'

react-native-material-dropdown/test/DropDownTest.tsx
请解释此次更改的 **动机**，以下是一些帮助您的要点
这个PR不涉及到issues
修改react-native-material-dropdown测试用例
- 您是如何实现解决方案的？
按照要求修改测试demo用例
demo修改，不涉及源库
demo地址：https://github.com/react-native-oh-library/RNOHDCS/tree/main/react-native-material-dropdown
=> test: 修改react-native-material-dropdown测试用例

react-native-ssl-pinning/SslPinningDemo.tsx
1: 修改react-native-ssl-pinning的demo
=> test: 修改react-native-ssl-pinning的demo

react-native-ffmpeg-kit/test-app-npm/src/audio-tab.js, react-native-ffmpeg-kit/test-app-npm/src/main.js, react-native-ffmpeg-kit/test-app-npm/src/other-tab.js, react-native-ffmpeg-kit/test-app-npm/src/pipe-tab.js, react-native-ffmpeg-kit/test-app-npm/src/style.js, react-native-ffmpeg-kit/test-app-npm/src/video-tab.js
- 新增 opus 测试场景
- 新增 speex 测试场景
- 新增 openh264 测试场景
- 新增 webp 测试场景
=> test:修改ffmpeg-kit三方库demo，新增测试场景

react-native-ffmpeg-kit/command-tab.js, react-native-ffmpeg-kit/concurrent-execution-tab.js
- 新增isSuccess属性失败场景。
- 获取ffprobsession中的属性。
- 获取ffmpegsession中的属性。
- 展示clearsession前后的效果。
=> 新增ffmpeg-kit测试属性

ant-design-mobile-rn/ListTest.tsx
- test:修改ant-design-mobile-rn中demo居中对齐和顶部居中的显示问题
=> test:修改ant-design-mobile-rn中demo居中对齐和顶部居中的显示问题

react-native-gesture-handler/App.tsx, react-native-gesture-handler/DDGestureDemo.tsx
- 新增pan和捏合手势的混合场景；
- 修复触摸点个数不正确的问题；
- 处理连续双击夹杂打击的问题。
=> test: 添加gesture-handler手势库测试场景

pull_to_refresh/CustomPullToRefreshFooter.tsx, pull_to_refresh/PullRefreshFlatList/FlatListPage.tsx, pull_to_refresh/PullRefreshFlatList/index.tsx, pull_to_refresh/SpinnerPullToRefreshHeader.tsx
- test:新增@react-native-oh-tpl/pull_to_refresh的demo
- closed: #1692
=> test:新增@react-native-oh-tpl/pull_to_refresh的demo

react-native-text-shadow/App1.js
- test:新增react-native-text-shadow的demo
=> test:新增react-native-text-shadow的demo
